name: Build AKS Image
permissions:
  contents: none

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
# The `workflow_dispatch` had been added to be able to run the
# workflow manually (for testing purposes).
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Call Azure
        uses: amsterdam/trigger-ado-pipeline@v1
        with:
          pipeline-id: ${{ secrets.AZURE_DEVOPS_PIPELINE_ID }}
          organisation: ${{ secrets.AZURE_DEVOPS_ORG }}
          project: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          pat-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          template-params: '{"environment": "- dev\n- test\n- acc", "branch": "main", "akscluster": "blue", "includeSql": "v2"}'
